layout_spectrum: 0.2843623114608708
typography_spectrum: 0.27702376880378715
color:
  brandStrength: 0.6166190753523998
  lightness: 0.5451740243717438
  saturation: 0.03362870904921305
  rhythmicContrast: 0.7458568893346271
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/f7d3e4d7-045d-4d6c-9609-88dc0fdce5e5.jpg
logo: null
name: EVE
navigation:
  - name: About?
    id: edbbd517-0b3c-4543-b1b8-27acdb80f324
    type: content
  - name: Twitter
    url: 'https://twitter.com/meh301'
    type: external
  - name: Instagram
    url: 'https://www.instagram.com/meh301/'
    type: external
  - name: VSCO
    url: 'http://vsco.co/meh301/images/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/531ad4dc-257b-47cd-b35f-476c3ac583be.jpg
content: []
purpose: []
