layout_spectrum: 0.5215474489779387
typography_spectrum: 0.33138622605112744
color:
  brandStrength: 0.44890308382948585
  lightness: 0.08632725173773446
  saturation: 0.1155068021036205
  rhythmicContrast: 0.9142845028323481
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/f7d3e4d7-045d-4d6c-9609-88dc0fdce5e5.jpg
logo: null
name: EVE
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/531ad4dc-257b-47cd-b35f-476c3ac583be.jpg
title: ''
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/3af0d868-7ab8-49f2-aa19-627a128b57a7.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/3af0d868-7ab8-49f2-aa19-627a128b57a7.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/1da07677-1da2-47af-8d68-3a0417bb6aae.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/1da07677-1da2-47af-8d68-3a0417bb6aae.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ''
purpose:
  - type: external
    url: 'http://minerva.photo'
    label: Photography
  - type: external
    url: 'http://alexorsholits.art'
    label: Academic Portfolio
