layout_spectrum: 0.5215474489779387
typography_spectrum: 0.33138622605112744
color:
  brandStrength: 0.44890308382948585
  lightness: 0.08632725173773446
  saturation: 0.1155068021036205
  rhythmicContrast: 0.9142845028323481
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/f7d3e4d7-045d-4d6c-9609-88dc0fdce5e5.jpg
logo: null
name: EVE
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/531ad4dc-257b-47cd-b35f-476c3ac583be.jpg
title: ''
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FV0NWNnRLRug%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DV0NWNnRLRug&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FV0NWNnRLRug%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Alex Orsholits
          url: 'https://www.youtube.com/channel/UCpB5Skp4h7EszTAb0BF8ZCQ'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: www.youtube.com
      keywords:
        - video
        - sharing
        - camera phone
        - video phone
        - free
        - upload
      description: Uploaded by Alex Orsholits on 2017-09-24.
      '@type': VideoObject
      app_links: []
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=V0NWNnRLRug'
      title: 00025 1
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Alex Orsholits - Personal Portfolio
purpose:
  - type: external
    url: 'http://minerva.photo'
    label: Photography
  - type: external
    url: 'http://alexorsholits.art'
    label: Academic Portfolio
