typography_spectrum: 0.27702376880378715
color:
  brandStrength: 0.6166190753523998
  lightness: 0.5451740243717438
  saturation: 0.03362870904921305
  rhythmicContrast: 0.7458568893346271
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/f7d3e4d7-045d-4d6c-9609-88dc0fdce5e5.jpg
layout_spectrum: 0.2843623114608708
logo: null
name: EVE
navigation:
  - name: About?
    id: edbbd517-0b3c-4543-b1b8-27acdb80f324
    type: content
  - name: Twitter
    url: 'https://twitter.com/meh301'
    type: external
  - name: VSCO
    url: 'http://vsco.co/meh301/images/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/531ad4dc-257b-47cd-b35f-476c3ac583be.jpg
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/6c13e7a6-ca69-4093-b5bf-9705f69017c5.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/6c13e7a6-ca69-4093-b5bf-9705f69017c5.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
purpose: []
title: EVE
description: Personal Portfolio
