typography_spectrum: 0.27702376880378715
color:
  brandStrength: 0.6166190753523998
  lightness: 0.5451740243717438
  saturation: 0.03362870904921305
  rhythmicContrast: 0.7458568893346271
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/f7d3e4d7-045d-4d6c-9609-88dc0fdce5e5.jpg
layout_spectrum: 0.2843623114608708
logo: null
name: EVE
navigation:
  - name: Twitter
    url: 'https://twitter.com/meh301'
    type: external
  - name: VSCO
    url: 'http://vsco.co/meh301/images/'
    type: external
  - name: Minerva
    url: 'https://minerva.photo'
    type: external
  - name: Flickr
    url: 'https://www.flickr.com/photos/48082093@N05/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/531ad4dc-257b-47cd-b35f-476c3ac583be.jpg
title: EVE
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/224769fd-fd44-48e2-8c49-723d7edc6b73.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/224769fd-fd44-48e2-8c49-723d7edc6b73.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Personal Portfolio
purpose:
  - type: contact
    url: 'mailto:alex.orsholits@epfl.ch'
    label: Contact
