layout_spectrum: 0.1468138824720489
typography_spectrum: 0.32264960179326707
color:
  brandStrength: 0.4461944173625901
  lightness: 0.08767388314442101
  saturation: 0.11439921148019926
  rhythmicContrast: 0.7420945632396875
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/f7d3e4d7-045d-4d6c-9609-88dc0fdce5e5.jpg
logo: null
name: EVE
navigation:
  - name: Twitter
    url: 'https://twitter.com/meh301'
    type: external
  - name: VSCO
    url: 'http://vsco.co/meh301/images/'
    type: external
  - name: Flickr
    url: 'https://www.flickr.com/photos/48082093@N05/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/531ad4dc-257b-47cd-b35f-476c3ac583be.jpg
title: EVE
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/224769fd-fd44-48e2-8c49-723d7edc6b73.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/224769fd-fd44-48e2-8c49-723d7edc6b73.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Personal Portfolio
purpose:
  - type: contact
    url: 'mailto:alex.orsholits@epfl.ch'
    label: Contact me
  - type: external
    url: 'http://minerva.photo'
    label: Photography
